
llm: # used for report extraction
  LLM_type: openai # Options: openai, gemini, ollama, vllm
  LLM_model: gpt-4o-mini # Replace with your desired model name

#⛔️ Caution: Local interpretation should only be used with multimodal models. Currently supporting OLLAMA. VLLM is so soon! ⛔️'
image_interpreter:
  ignore_img_not_found: False
  image_formats:
    - 'png' # png is default for reddit
  image_field: 'url'
  host: 'ollama'
  model: 'llava'

classifier:
  history_path: templates/history.json


all_eyes_on_reddit:
  criteria: 'to be implemented later'
  main_field: 'title'
  other_fields:
    - 'selftext'
    - 'score'
    - 'num_comments'
  author_field: 'author'
  template: templates/subreddit.j2
  user_template: 'templates/security2.j2'
  sub_template: 'templates/sub_per_user.j2'
  reddit_: 'r/Turkey'
  use_images: False

  