prompt_gen:
  json_path: ''
  template_path: 'templates/subreddit.j2'
  text_field: title
  other_fields:
    - 'selftext'
    - 'author'
    - 'score'
    - 'num_comments'
  handle_pics: True

image_interpreter:
  image_formats:
    - 'png' # png is default for reddit
  image_field: 'url'
  max_new_tokens: 512
  use_local_model: False
  model: gpt-4o-mini

  
classifier:
  model: gpt-4o-mini
  history_path: templates/history.json
  query:
    - 'location'
    - 'real name'
    - 'age'