prompt_gen:
  json_path: ''
  template_path: 'templates/subreddit.j2'
  text_field: title
  other_fields:
    - 'score'
    - 'num_comments'
    - 'selftext'

  
classifier:
  model: gpt-4o-mini
  history_path: templates/history.json
  query:
    - 'location'
    - 'real name'
    - 'age'